"""Shared configuration for the final 15-case virtual try-on demo."""

from .config import (
    CANVAS_SIZE,
    DATA_INPUT_ROOT,
    DEFAULT_FINAL_EVAL_ROOT,
    DEFAULT_FINAL_OUTPUT_ROOT,
    FINAL_METHODS,
    FINAL_PASS_PLAN,
    GARMENT_FILE_BY_REGION,
    REGION_LABELS,
    SOURCE_SAMPLE_PLAN,
    MethodSpec,
    SourceItemSpec,
    category_for_regions,
    final_method_paths,
    garment_file_for_region,
    item_description,
    local_pass_seed,
    region_prompt,
    sample_id_for_index,
    sample_region,
)

__all__ = [
    "CANVAS_SIZE",
    "DATA_INPUT_ROOT",
    "DEFAULT_FINAL_EVAL_ROOT",
    "DEFAULT_FINAL_OUTPUT_ROOT",
    "FINAL_METHODS",
    "FINAL_PASS_PLAN",
    "GARMENT_FILE_BY_REGION",
    "REGION_LABELS",
    "SOURCE_SAMPLE_PLAN",
    "MethodSpec",
    "SourceItemSpec",
    "category_for_regions",
    "final_method_paths",
    "garment_file_for_region",
    "item_description",
    "local_pass_seed",
    "region_prompt",
    "sample_id_for_index",
    "sample_region",
]
